# Generated by Django 3.2 on 2021-04-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('Title', models.CharField(max_length=300)),
                ('Description', models.TextField(blank=True)),
                ('Field', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('FileUpload', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
