# Generated by Django 3.2 on 2021-04-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfiles',
            name='FileUpload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
