# Generated by Django 3.2 on 2021-04-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalfile', '0002_alter_digitalfiles_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfiles',
            name='FileUpload',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
