# Generated by Django 3.2 on 2021-04-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalfile', '0003_alter_digitalfiles_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalfiles',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='digitalfiles',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='digitalfiles',
            old_name='surname',
            new_name='Surname',
        ),
    ]
